#! /bin/bash
setfont cyr-sun16
echo -n"
1. EFI режиме
2. Legacy режиме
Каком режиме вы хотите установить систему"
read systemgrub
if (($systemgrub == 1)); then
    echo -n "Выберете раздел для EFI (sda1,sdb2 и т.п):"
       read efifs
       mkfs.fat -F 32 /dev/$efifs
fi
clear
lsblk
echo -n "Выберете раздел для roofs(/) (sda1,sdb2 и т.п): "
read root
echo -n "
1.BTRFS
2.EXT4
3.XFS
Выберете файловую систему: "
read fsroot
if (($fsroot == 1)); then
    mkfs.btrfs -f /dev/$root
elif (($fsroot == 2)); then
    mkfs.ext4 /dev/$root
elif (($fsroot == 3)); then
    mkfs.xfs /dev/$root
else
    echo "Неверный параментр"
fi
clear
lsblk
echo -n "
1. Нет
2. Да
Нужно ли создавать раздел /home?: "
read homeys
if (($homeys == 2)); then
lsblk
echo -n "Выберете раздел для /home (sda1,sdb2 и т.п): "
read home
echo -n "
1.BTRFS
2.EXT4
3.XFS
Выберете файловую систему: "
read fshome
else 
    echo "Неверно"
fi
if (($fshome == 1)) && (($homeys == 2)); then
    mkfs.btrfs -f /dev/$home
    mkdir /mnt/home
    mount /dev/$home /mnt/home
elif (($fshome == 2)) && (($homeys == 2)); then
    mkfs.aext4 /dev/$home
    mkdir /mnt/home
    mount /dev/$home /mnt/home
elif (($fshome == 3)) && (($homeys == 2)); then
    mkfs.xfs /dev/$home
    mkdir /mnt/home
    mount /dev/$home /mnt/home
elif (($homeys == 1)); then
    clear
else
    echo "Неверный параментр"
fi
claer
mount /dev/$root /mnt
if (($systemgrub == 1)); then
    mkdir /boot
    mkdir /boot/efi
   mount /dev/$efifs /mnt/boot/efi
fi
echo 'Server = http://mirror.hoster.kz/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
echo -n "
1.Linux
2.Linux ZEN
3.Linux LTS
Выберете ядро системы: "
read kernel
if (($kernel == 1)) && (($fsroot == 1)); then
    pacstrap /mnt base linux linux-firmware linux-headers base-devel sudo nano btrfs-progs
elif (($kernel == 2)) && (($fsroot == 1)); then
    pacstrap /mnt base linux-zen linux-firmware linux-zen-headers base-devel sudo nano btrfs-progs
elif (($kernel == 3)) && (($fsroot == 1)); then
    pacstrap /mnt base linux-lts linux-firmware linux-lts-headers base-devel sudo nano btrfs-progs
elif (($kernel == 1));then
    pacstrap /mnt base linux linux-firmware linux-headers base-devel sudo nano 
elif (($kernel == 2)); then
    pacstrap /mnt base linux-zen linux-firmware linux-zen-headers base-devel sudo nano 
elif (($kernel == 3)); then
    pacstrap /mnt base linux-lts linux-firmware linux-lts-headers base-devel sudo nano 
else echo "Неверный параментр"
fi
genfstab -U /mnt >> /mnt/etc/fstab
cp test.sh /mnt 
arch-chroot /mnt 
echo -n "
1.Русский
2.Английский
Выберете язык системы: "
read leag
if (($leag == 1)); then
   echo ru_RU.UTF-8 >> /etc/locale.gen
   echo en_US.UTF-8 >> /etc/locale.gen
   locale-gen
   echo LANG=ru_RU.UTF-8 >> /etc/locale.conf
   echo KEYMAP=ru >> /etc/vconsole.conf
   echo FONT=cyr-sun16 >> FONT=cyr-sun16
elif (($leag == 2)); then
    clear
else echo "Неверный параментр"
fi
clear
echo "Введите имя компьютера: "
read name
echo $name >> /etc/hostname

echo "Введите пароль от Root"
passwd root
if (($systemgrub == 1)); then
    pacman -S networkmanager grub efibootmgr
    grub-install 
    grub-mkconfig -o /boot/grub/grub.cfg
elif (($systemgrub = 2)); then
    echo -n "Выберете на какой диск будет установлен GRUB (sda,sdb и т.п): "
    read $grub
    pacman -S networkmanager grub
    grub-install /dev/$grub
    grub-mkconfig /boot/grub/grub.cfg
fi
systemctl enable networkmanager
clear
echo "Установка успешно завершена"
exit 
reboot


